PROJECT = "LuatOS-SoC-Test"
VERSION = "1.0.0"
MOD_TYPE = rtos.bsp()
log.info("MOD_TYPE", MOD_TYPE)

sys = require("sys")

sys.taskInit(function()
    -- require("adcTest").test()
    -- require("cryptoTest").test()
    -- require("fdbTest").test()
    -- require("i2cTest").test()
    -- require("fsTest").test()
    -- require("gpioTest").test()
    -- require("jsonTest").test()
    -- require("pwmTest").test()
    -- require("mcuTest").test()
    -- require("pinTest").test()
    -- require("rtcTest").test()
    -- require("rtosTest").test()
    -- require("stringTest").test()
    -- require("zbuffTest").test()
    -- require("wlanTest").test()
    -- require("socketTest").test()
    -- require("mqttTest").test()
    require("bleTest").test()
    require("esp32Test").test()
    require("espnowTest").test()
    -- require("cameraTest").test()
end)

sys.run()
