function GaugeInit()
     Gauge1 = lvgl.gauge_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(Gauge1,200,200)
     lvgl.obj_align(Gauge1,Father,lvgl.ALIGN_CENTER,-110,-150)
     lvgl.gauge_set_needle_count(Gauge1,1,lvgl.color_hex(0xFFFF00))
     lvgl.gauge_set_value(Gauge1,0,30)

     Gauge2 = lvgl.gauge_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(Gauge2,200,200)
     lvgl.gauge_set_range(Gauge2,0,200)
     lvgl.obj_align(Gauge2,Father,lvgl.ALIGN_CENTER,110,-150)
     lvgl.gauge_set_needle_count(Gauge2,10,lvgl.color_hex(0xFFFF00))
     lvgl.gauge_set_value(Gauge2,0,10)
     lvgl.gauge_set_value(Gauge2,1,30)
     lvgl.gauge_set_value(Gauge2,2,50)
     lvgl.gauge_set_value(Gauge2,3,70)
     lvgl.gauge_set_value(Gauge2,4,90)
     lvgl.gauge_set_value(Gauge2,5,110)
     lvgl.gauge_set_value(Gauge2,6,130)
     lvgl.gauge_set_value(Gauge2,7,150)
     lvgl.gauge_set_value(Gauge2,8,170)
     lvgl.gauge_set_value(Gauge2,9,190)

     Gauge3 = lvgl.gauge_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(Gauge3,200,200)
     lvgl.gauge_set_range(Gauge3,0,100)
     lvgl.obj_align(Gauge3,Father,lvgl.ALIGN_CENTER,-110,150)
     lvgl.gauge_set_needle_count(Gauge3,1,lvgl.color_hex(0xFFFF00))
     lvgl.gauge_set_critical_value(Gauge3,90)
     lvgl.gauge_set_value(Gauge3,0,30)
     lvgl.gauge_set_scale(Gauge3,320,51,11)
     
     Gauge4 = lvgl.gauge_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(Gauge4,200,200)
     lvgl.gauge_set_range(Gauge3,-100,100)
     lvgl.obj_align(Gauge4,Father,lvgl.ALIGN_CENTER,110,150)
     lvgl.gauge_set_needle_count(Gauge4,1,lvgl.color_hex(0x0000FF))
     lvgl.gauge_set_value(Gauge4,0,30)
     lvgl.gauge_set_angle_offset(Gauge4,90)
    --  lvgl.gauge_set_needle_img(Gauge4,lvgl)
    -- lvgl.gauge_set_formatter_cb(Gauge4,x) 

end


