function LabelInit()
	Label1 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text_sel_start(Label1,20)
	lvgl.label_set_text_sel_end(Label1,25)
    lvgl.label_set_text(Label1,"传说中niweiaiganxinbeigeqian，woyekeyiweiniqianruhailimian")
	lvgl.label_set_long_mode(Label1,lvgl.LABEL_LONG_SROLL_CIRC)
	lvgl.obj_set_width(Label1, 200)
	lvgl.obj_align(Label1,Father,lvgl.ALIGN_CENTER,0,-400)
	lvgl.obj_add_style(Label1, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
    lvgl.label_set_anim_speed(Label1,10)

	Label2 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label2,"传说中niweiaiganxinbeigeqian，woyekeyiweiniqianruhailimian")
	lvgl.label_set_long_mode(Label2,lvgl.LABEL_LONG_SROLL)
	lvgl.obj_set_width(Label2,200)
	lvgl.obj_align(Label2,Father,lvgl.ALIGN_CENTER,0,-350)
	lvgl.obj_add_style(Label2, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
	

	Label3 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label3,"传说中niweiaiganxinbeigeqian，woyekeyiweiniqianruhailimian")
	lvgl.label_set_long_mode(Label3,lvgl.LABEL_LONG_DOT)
	lvgl.obj_set_width(Label3,200)
	lvgl.obj_align(Label3,Father,lvgl.ALIGN_CENTER,0,-300)
	lvgl.obj_add_style(Label3, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
	
	Label4 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label4,"传说中niweiaiganxinbeigeqian，woyekeyiweiniqianruhailimian")
	lvgl.label_set_long_mode(Label4,lvgl.LABEL_LONG_BREAK)
	lvgl.obj_set_width(Label4,200)
	lvgl.obj_align(Label4,Father,lvgl.ALIGN_CENTER,0,-250)
	lvgl.obj_add_style(Label4, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
	
	Label5 = lvgl.label_create(lvgl.scr_act(),nil)
	-- lvgl.label_set_text_sel_start(Label5,20)
	-- lvgl.label_set_text_sel_end(Label5,25)
	lvgl.label_set_text(Label5,"niweiaiganxinbeigeqian，woyekeyiweiniqianruhailimian")
	lvgl.label_set_long_mode(Label5,lvgl.LABEL_LONG_EXPAND)
	lvgl.obj_set_width(Label5,200)
	lvgl.obj_align(Label5,Father,lvgl.ALIGN_CENTER,0,-200)
	lvgl.obj_add_style(Label5, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)

	Label6 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label6,"传说中niweiaiganxinbeigeqian，woyekeyiweiniqianruhailimian")
	lvgl.label_set_long_mode(Label6,lvgl.LABEL_LONG_CROP)
	lvgl.obj_set_width(Label6,200)
	lvgl.obj_align(Label6,Father,lvgl.ALIGN_CENTER,0,-150)
	lvgl.obj_add_style(Label6, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
	
	Label7 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label7,"传说中niweiaiganxinbeigeqian，woyekeyiweiniqianruhailimian")
	lvgl.label_set_long_mode(Label7,lvgl.LABEL_LONG_BREAK)
	lvgl.obj_set_width(Label7,200)
	lvgl.obj_align(Label7,Father,lvgl.ALIGN_CENTER,0,-100)
	lvgl.label_set_align(Label7,lvgl.LABEL_ALIGN_RIGHT)
	lvgl.obj_add_style(Label7, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
	
	Label8 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label8,"#0000ff 传说中niweiaiganxinbeigeqian，woyekeyiweiniqianruhailimian")
	lvgl.label_set_long_mode(Label8,lvgl.LABEL_LONG_BREAK)
	lvgl.obj_set_width(Label8,200)
	lvgl.obj_align(Label8,Father,lvgl.ALIGN_CENTER,0,-20)
	lvgl.label_set_recolor(Label8,false)
	lvgl.obj_add_style(Label8, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
	

	Label9 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label9,"#0000ff 传说中niweiaiganxinbeigeq #ff00ff ian，woyekeyiweiniqianruhailimian")
	lvgl.label_set_long_mode(Label9,lvgl.LABEL_LONG_BREAK)
	lvgl.obj_set_width(Label9,200)
	lvgl.obj_align(Label9,Father,lvgl.ALIGN_CENTER,0,70)
	lvgl.label_set_recolor(Label9,true)
	lvgl.obj_add_style(Label9, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
	
end