function LabelInit()
	Label1 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text_sel_start(Label1,20)
	lvgl.label_set_text_sel_end(Label1,25)
    lvgl.label_set_text(Label1,"测试chuanshuozhongniweiaiganxinbeigeqian")
	lvgl.label_set_long_mode(Label1,lvgl.LABEL_LONG_SROLL_CIRC)
	lvgl.obj_set_width(Label1, 200)
	lvgl.obj_align(Label1,Father,lvgl.ALIGN_IN_TOP_MID,0,0)
	lvgl.obj_add_style(Label1, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
    lvgl.label_set_anim_speed(Label1,10)

	label1 = lvgl.label_create(lvgl.scr_act(),nil)
    lvgl.label_set_text(label1,"获取标签的文本:"..lvgl.label_get_text(Label1).."\n获取标签的长模式:"..lvgl.label_get_long_mode(Label1).."                获取对齐属性:"..lvgl.label_get_align(Label1).."\n获取重新着色属性:"..tostring(lvgl.label_get_recolor(Label1)).."            获取动画的速度:"..lvgl.label_get_anim_speed(Label1))
    lvgl.obj_align(label1,nil,lvgl.ALIGN_IN_TOP_LEFT,0,20)
    lvgl.obj_add_style(label1, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)

	Label2 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label2,"测试chuanshuozhongniweiaiganxinbeigeqian")
	lvgl.label_set_long_mode(Label2,lvgl.LABEL_LONG_SROLL)
	lvgl.obj_set_width(Label2,200)
	lvgl.obj_align(Label2,Father,lvgl.ALIGN_IN_TOP_MID,0,70)
	lvgl.obj_add_style(Label2, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
	
	label2 = lvgl.label_create(lvgl.scr_act(),nil)
    lvgl.label_set_text(label2,"获取标签的文本:"..lvgl.label_get_text(Label2).."\n获取标签的长模式:"..lvgl.label_get_long_mode(Label2).."                获取对齐属性:"..lvgl.label_get_align(Label2).."\n获取重新着色属性:"..tostring(lvgl.label_get_recolor(Label2)).."            获取动画的速度:"..lvgl.label_get_anim_speed(Label2))
    lvgl.obj_align(label2,nil,lvgl.ALIGN_IN_TOP_LEFT,0,90)
    lvgl.obj_add_style(label2, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)

	Label3 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label3,"测试chuanshuozhongniweiaiganxinbeigeqian")
	lvgl.label_set_long_mode(Label3,lvgl.LABEL_LONG_DOT)
	lvgl.obj_set_width(Label3,200)
	lvgl.obj_align(Label3,Father,lvgl.ALIGN_IN_TOP_MID,0,140)
	lvgl.obj_add_style(Label3, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
	
	label3 = lvgl.label_create(lvgl.scr_act(),nil)
    lvgl.label_set_text(label3,"获取标签的文本:"..lvgl.label_get_text(Label3).."\n获取标签的长模式:"..lvgl.label_get_long_mode(Label3).."                获取对齐属性:"..lvgl.label_get_align(Label3).."\n获取重新着色属性:"..tostring(lvgl.label_get_recolor(Label3)).."            获取动画的速度:"..lvgl.label_get_anim_speed(Label3))
    lvgl.obj_align(label3,nil,lvgl.ALIGN_IN_TOP_LEFT,0,160)
    lvgl.obj_add_style(label3, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)

	Label4 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label4,"测试chuanshuozhongniweiaiganxinbeigeqian")
	lvgl.label_set_long_mode(Label4,lvgl.LABEL_LONG_BREAK)
	lvgl.obj_set_width(Label4,200)
	lvgl.obj_align(Label4,Father,lvgl.ALIGN_IN_TOP_MID,0,210)
	lvgl.obj_add_style(Label4, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)

	label4 = lvgl.label_create(lvgl.scr_act(),nil)
    lvgl.label_set_text(label4,"获取标签的文本:"..lvgl.label_get_text(Label4).."\n获取标签的长模式:"..lvgl.label_get_long_mode(Label4).."                获取对齐属性:"..lvgl.label_get_align(Label4).."\n获取重新着色属性:"..tostring(lvgl.label_get_recolor(Label4)).."            获取动画的速度:"..lvgl.label_get_anim_speed(Label4))
    lvgl.obj_align(label4,nil,lvgl.ALIGN_IN_TOP_LEFT,0,250)
    lvgl.obj_add_style(label4, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)
	
	Label5 = lvgl.label_create(lvgl.scr_act(),nil)
	-- lvgl.label_set_text_sel_start(Label5,20)
	-- lvgl.label_set_text_sel_end(Label5,25)
	lvgl.label_set_text(Label5,"测试chuanshuozhongniweiaiganxinbeigeqian")
	lvgl.label_set_long_mode(Label5,lvgl.LABEL_LONG_EXPAND)
	lvgl.obj_set_width(Label5,200)
	lvgl.obj_align(Label5,Father,lvgl.ALIGN_IN_TOP_MID,0,300)
	lvgl.obj_add_style(Label5, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)

	label5 = lvgl.label_create(lvgl.scr_act(),nil)
    lvgl.label_set_text(label5,"获取标签的文本:"..lvgl.label_get_text(Label5).."\n获取标签的长模式:"..lvgl.label_get_long_mode(Label5).."                获取对齐属性:"..lvgl.label_get_align(Label5).."\n获取重新着色属性:"..tostring(lvgl.label_get_recolor(Label5)).."            获取动画的速度:"..lvgl.label_get_anim_speed(Label5))
    lvgl.obj_align(label5,nil,lvgl.ALIGN_IN_TOP_LEFT,0,320)
    lvgl.obj_add_style(label5, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)

	Label6 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label6,"测试chuanshuozhongniweiaiganxinbeigeqian")
	lvgl.label_set_long_mode(Label6,lvgl.LABEL_LONG_CROP)
	lvgl.obj_set_width(Label6,200)
	lvgl.obj_align(Label6,Father,lvgl.ALIGN_IN_TOP_MID,0,370)
	lvgl.obj_add_style(Label6, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
	
	label6 = lvgl.label_create(lvgl.scr_act(),nil)
    lvgl.label_set_text(label6,"获取标签的文本:"..lvgl.label_get_text(Label6).."\n获取标签的长模式:"..lvgl.label_get_long_mode(Label6).."                获取对齐属性:"..lvgl.label_get_align(Label6).."\n获取重新着色属性:"..tostring(lvgl.label_get_recolor(Label6)).."            获取动画的速度:"..lvgl.label_get_anim_speed(Label6))
    lvgl.obj_align(label6,nil,lvgl.ALIGN_IN_TOP_LEFT,0,390)
    lvgl.obj_add_style(label6, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)

	Label7 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label7,"测试chuanshuozhongniweiaiganxinbeigeqian")
	lvgl.label_set_long_mode(Label7,lvgl.LABEL_LONG_BREAK)
	lvgl.obj_set_width(Label7,200)
	lvgl.obj_align(Label7,Father,lvgl.ALIGN_IN_TOP_MID,0,440)
	lvgl.label_set_align(Label7,lvgl.LABEL_ALIGN_RIGHT)
	lvgl.obj_add_style(Label7, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)

	label7 = lvgl.label_create(lvgl.scr_act(),nil)
    lvgl.label_set_text(label7,"获取标签的文本:"..lvgl.label_get_text(Label7).."\n获取标签的长模式:"..lvgl.label_get_long_mode(Label7).."                获取对齐属性:"..lvgl.label_get_align(Label7).."\n获取重新着色属性:"..tostring(lvgl.label_get_recolor(Label7)).."            获取动画的速度:"..lvgl.label_get_anim_speed(Label7))
    lvgl.obj_align(label7,nil,lvgl.ALIGN_IN_TOP_LEFT,0,480)
    lvgl.obj_add_style(label7, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)
	
	Label8 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label8,"#0000ff 测试chuanshuozhongniweiaiganxinbeigeqian")
	lvgl.label_set_long_mode(Label8,lvgl.LABEL_LONG_BREAK)
	lvgl.obj_set_width(Label8,200)
	lvgl.obj_align(Label8,Father,lvgl.ALIGN_IN_TOP_MID,0,530)
	lvgl.label_set_recolor(Label8,false)
	lvgl.obj_add_style(Label8, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)
	
	label8 = lvgl.label_create(lvgl.scr_act(),nil)
    lvgl.label_set_text(label8,"获取标签的文本:"..lvgl.label_get_text(Label8).."\n获取标签的长模式:"..lvgl.label_get_long_mode(Label8).."                获取对齐属性:"..lvgl.label_get_align(Label8).."\n获取重新着色属性:"..tostring(lvgl.label_get_recolor(Label8)).."            获取动画的速度:"..lvgl.label_get_anim_speed(Label8))
    lvgl.obj_align(label8,nil,lvgl.ALIGN_IN_TOP_LEFT,0,590)
    lvgl.obj_add_style(label8, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)

	Label9 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label9,"#0000ff 测试chuanshuozhong #ff00ff niweiaiganxinbeigeqian")
	lvgl.label_set_long_mode(Label9,lvgl.LABEL_LONG_BREAK)
	lvgl.obj_set_width(Label9,200)
	lvgl.obj_align(Label9,Father,lvgl.ALIGN_IN_TOP_MID,0,640)
	lvgl.label_set_recolor(Label9,true)
	lvgl.obj_add_style(Label9, lvgl.LABEL_PART_MAIN, demo_ThemeFontStyle)

	label9 = lvgl.label_create(lvgl.scr_act(),nil)
    lvgl.label_set_text(label9,"获取标签的文本:"..lvgl.label_get_text(Label9).."\n获取标签的长模式:"..lvgl.label_get_long_mode(Label9).."                获取对齐属性:"..lvgl.label_get_align(Label9).."\n获取重新着色属性:"..tostring(lvgl.label_get_recolor(Label9)).."             获取动画的速度:"..lvgl.label_get_anim_speed(Label9))
    lvgl.obj_align(label9,nil,lvgl.ALIGN_IN_TOP_LEFT,0,680)
    lvgl.obj_add_style(label9, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)
	
end