function ListInit()
     List1 = lvgl.list_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(List1,150,200)
	 lvgl.obj_align(List1,Father,lvgl.ALIGN_IN_TOP_LEFT,0,0)
     lvgl.list_add_btn(List1,lvgl.SYMBOL_NEW_LINE,"星期一")
	 btn1 = lvgl.list_add_btn(List1, lvgl.SYMBOL_DIRECTORY, "Open")
	 lvgl.list_add_btn(List1, lvgl.SYMBOL_CLOSE, "Delete")
	 lvgl.list_add_btn(List1, lvgl.SYMBOL_EDIT, "Edit")
	 lvgl.list_add_btn(List1, lvgl.SYMBOL_USB, "USB")
	 lvgl.list_add_btn(List1, lvgl.SYMBOL_GPS, "GPS")
	 lvgl.list_add_btn(List1, lvgl.SYMBOL_STOP, "Stop")
	 lvgl.list_add_btn(List1, lvgl.SYMBOL_VIDEO, "Video")
     
	 Label1 = lvgl.label_create(lvgl.scr_act(),nil)
	 lvgl.label_set_text(Label1,"获取列表的文本:"..lvgl.list_get_btn_text(btn1).."\n获取标签对象:"..tostring(lvgl.list_get_btn_label(btn1)).."\n获取图像对象:"..tostring(lvgl.list_get_btn_img(btn1)).."\n从列表中按钮索引:"..tostring(lvgl.list_get_btn_index(List1,btn1)).."\n获取列表中的按钮个数:"..lvgl.list_get_size(List1).."\n获取列表的布局:"..tostring(lvgl.list_get_layout(List1)).."\n获取列表的滚动条模式:"..lvgl.list_get_scrollbar_mode(List1).."\n获取滚动传播属性:"..tostring(lvgl.list_get_scroll_propagation(List1)).."\n获取滚动传播属性:"..tostring(lvgl.list_get_edge_flash(List1)).."\n获取滚动动画持续时间:"..lvgl.list_get_anim_time(List1))
	 lvgl.obj_align(Label1,nil,lvgl.ALIGN_IN_TOP_LEFT,200,0)
	 lvgl.obj_add_style(Label1, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)

     List2 = lvgl.list_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(List2,150,200)
	 lvgl.obj_align(List2,Father,lvgl.ALIGN_IN_LEFT_MID,0,0)
	 lvgl.list_set_layout(List2,lvgl.LAYOUT_COLUMN_RIGHT)
	 lvgl.list_add_btn(List2,lvgl.SYMBOL_NEW_LINE,"星期一")
	 lvgl.list_add_btn(List2, lvgl.SYMBOL_DIRECTORY, "Open")
	 lvgl.list_add_btn(List2, lvgl.SYMBOL_CLOSE, "Delete")
	 lvgl.list_add_btn(List2, lvgl.SYMBOL_EDIT, "Edit")
	 lvgl.list_add_btn(List2, lvgl.SYMBOL_USB, "USB")
	 btn2 = lvgl.list_add_btn(List2, lvgl.SYMBOL_GPS, "GPS")
	 lvgl.list_add_btn(List2, lvgl.SYMBOL_STOP, "Stop")
	 lvgl.list_add_btn(List2, lvgl.SYMBOL_VIDEO, "Video")
     lvgl.list_remove(List2,2)
	 lvgl.list_set_scrollbar_mode(List2,lvgl.SCROLLBAR_MODE_OFF)

	 Label2 = lvgl.label_create(lvgl.scr_act(),nil)
	 lvgl.label_set_text(Label2,"获取列表的文本:"..lvgl.list_get_btn_text(btn2).."\n获取标签对象:"..tostring(lvgl.list_get_btn_label(btn2)).."\n获取图像对象:"..tostring(lvgl.list_get_btn_img(btn2)).."\n从列表中按钮索引:"..tostring(lvgl.list_get_btn_index(List2,btn2)).."\n获取列表中的按钮个数:"..lvgl.list_get_size(List2).."\n获取列表的布局:"..tostring(lvgl.list_get_layout(List2)).."\n获取列表的滚动条模式:"..lvgl.list_get_scrollbar_mode(List2).."\n获取滚动传播属性:"..tostring(lvgl.list_get_scroll_propagation(List2)).."\n获取滚动传播属性:"..tostring(lvgl.list_get_edge_flash(List2)).."\n获取滚动动画持续时间:"..lvgl.list_get_anim_time(List2))
	 lvgl.obj_align(Label2,nil,lvgl.ALIGN_IN_LEFT_MID,200,0)
	 lvgl.obj_add_style(Label2, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)

	 List3 = lvgl.list_create(lvgl.scr_act(),nil)
	 lvgl.obj_set_size(List3,150,200)
	 lvgl.obj_align(List3,Father,lvgl.ALIGN_IN_BOTTOM_LEFT,0,0)
	 a = lvgl.list_add_btn(List3,lvgl.SYMBOL_NEW_LINE,"星期一")
	 b = lvgl.list_add_btn(List3, lvgl.SYMBOL_DIRECTORY, "Open")
	 c = lvgl.list_add_btn(List3, lvgl.SYMBOL_CLOSE, "Delete")
	 d = lvgl.list_add_btn(List3, lvgl.SYMBOL_EDIT, "Edit")
	 e = lvgl.list_add_btn(List3, lvgl.SYMBOL_USB, "USB")
	 f = lvgl.list_add_btn(List3, lvgl.SYMBOL_GPS, "GPS")
	 g = lvgl.list_add_btn(List3, lvgl.SYMBOL_STOP, "Stop")
	 h = lvgl.list_add_btn(List3, lvgl.SYMBOL_VIDEO, "Video")
	 lvgl.obj_add_style(List3, lvgl.LIST_PART_BG, demo_ThemeStyle_Bg)
	 lvgl.obj_add_style(a, lvgl.LIST_PART_BG, demo_ThemeStyle_Bg)
	 lvgl.obj_add_style(b, lvgl.LIST_PART_BG, demo_ThemeStyle_Bg)
	 lvgl.obj_add_style(c, lvgl.LIST_PART_BG, demo_ThemeStyle_Bg)
	 lvgl.obj_add_style(d, lvgl.LIST_PART_BG, demo_ThemeStyle_Bg)
	 lvgl.obj_add_style(e, lvgl.LIST_PART_BG, demo_ThemeStyle_Bg)
	 lvgl.obj_add_style(f, lvgl.LIST_PART_BG, demo_ThemeStyle_Bg)
	 lvgl.obj_add_style(g, lvgl.LIST_PART_BG, demo_ThemeStyle_Bg)
	 lvgl.obj_add_style(h, lvgl.LIST_PART_BG, demo_ThemeStyle_Bg)
	 lvgl.list_set_scrollbar_mode(List3,lvgl.SCROLLBAR_MODE_ON)
	 lvgl.list_focus_btn(List3,b)
	 lvgl.list_set_edge_flash(List3,true)
	 lvgl.list_set_anim_time(List3,500)
     
	 Label3 = lvgl.label_create(lvgl.scr_act(),nil)
	 lvgl.label_set_text(Label3,"获取列表的文本:"..lvgl.list_get_btn_text(e).."\n获取标签对象:"..tostring(lvgl.list_get_btn_label(e)).."\n获取图像对象:"..tostring(lvgl.list_get_btn_img(e)).."\n从列表中按钮索引:"..tostring(lvgl.list_get_btn_index(List3,e)).."\n获取列表中的按钮个数:"..lvgl.list_get_size(List3).."\n获取列表的布局:"..tostring(lvgl.list_get_layout(List3)).."\n获取列表的滚动条模式:"..lvgl.list_get_scrollbar_mode(List3).."\n获取滚动传播属性:"..tostring(lvgl.list_get_scroll_propagation(List3)).."\n获取滚动传播属性:"..tostring(lvgl.list_get_edge_flash(List3)).."\n获取滚动动画持续时间:"..lvgl.list_get_anim_time(List3))
	 lvgl.obj_align(Label3,nil,lvgl.ALIGN_IN_BOTTOM_LEFT,200,0)
	 lvgl.obj_add_style(Label3, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)


end