function PageInit()
	 Page1 = lvgl.page_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(Page1,100,150)
	 lvgl.obj_align(Page1,Father,lvgl.ALIGN_IN_TOP_LEFT,0,0)
     Btn1 = lvgl.btn_create(Page1,nil)
	 lvgl.obj_set_size(Btn1,70,30)
	 lvgl.obj_align(Btn1,Page1,lvgl.ALIGN_IN_TOP_LEFT,0,10)
	 Btn2 = lvgl.btn_create(Page1,nil)
	 lvgl.obj_set_size(Btn2,70,30)
	 lvgl.obj_align(Btn2,Page1,lvgl.ALIGN_IN_TOP_LEFT,0,50)
	 Btn3 = lvgl.btn_create(Page1,nil)
	 lvgl.obj_set_size(Btn3,70,30)
	 lvgl.obj_align(Btn3,Page1,lvgl.ALIGN_IN_TOP_LEFT,0,90)
	 Btn4 = lvgl.btn_create(Page1,nil)
	 lvgl.obj_set_size(Btn4,70,30)
	 lvgl.obj_align(Btn4,Page1,lvgl.ALIGN_IN_TOP_LEFT,0,130)
	 Btn5 = lvgl.btn_create(Page1,nil)
	 lvgl.obj_set_size(Btn5,70,30)
	 lvgl.obj_align(Btn5,Page1,lvgl.ALIGN_IN_TOP_LEFT,0,170)
     lvgl.page_set_scrollbar_mode(Page1,lvgl.SCROLLBAR_MODE_OFF)

	 Label1 = lvgl.label_create(lvgl.scr_act(),nil)
	 lvgl.label_set_text(Label1,"在页面上设置滚动条模式: "..lvgl.page_get_scrollbar_mode(Page1).."\n获取滚动传播属性: "..tostring(lvgl.page_get_scroll_propagation(Page1)).."\n获取边缘闪光效果属性: "..tostring(lvgl.page_get_edge_flash(Page1)).."\n获取可以设置给孩子的宽度仍然不会导致溢出: "..lvgl.page_get_width_fit(Page1).."\n获取可以设置给孩子的高度仍然不会导致溢出: "..lvgl.page_get_height_fit(Page1).."\n除以对象的宽度并获得给定数量的列的宽度:"..lvgl.page_get_width_grid(Page1).."\n除以对象的高度并获得给定数量的列的宽度: "..lvgl.page_get_height_grid(Page1).."\n获取页面可滚动部分的宽度: "..lvgl.page_get_scrl_width(Page1).."\n获取页面可滚动部分的高度: "..lvgl.page_get_scrl_height(Page1).."\n获取页面可滚动部分的布局: "..lvgl.page_get_scrl_layout(Page1).."\n获取最适合的模式: "..lvgl.page_get_scrl_fit_top(Page1).."\n获取底部贴合模式: "..lvgl.page_get_scrl_fit_bottom(Page1))
	 lvgl.obj_align(Label1,nil,lvgl.ALIGN_IN_TOP_RIGHT,0,0)
	 lvgl.obj_add_style(Label1, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)
     
	 Page2 = lvgl.page_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(Page2,100,150)
	 lvgl.obj_align(Page2,Father,lvgl.ALIGN_IN_TOP_LEFT,0,300)
     Btn1 = lvgl.btn_create(Page2,nil)
	 lvgl.obj_set_size(Btn1,70,30)
	 lvgl.obj_align(Btn1,Page2,lvgl.ALIGN_IN_TOP_LEFT,0,10)
	 Btn2 = lvgl.btn_create(Page2,nil)
	 lvgl.obj_set_size(Btn2,70,30)
	 lvgl.obj_align(Btn2,Page2,lvgl.ALIGN_IN_TOP_LEFT,0,50)
	 Btn3 = lvgl.btn_create(Page2,nil)
	 lvgl.obj_set_size(Btn3,70,30)
	 lvgl.obj_align(Btn3,Page2,lvgl.ALIGN_IN_TOP_LEFT,0,90)
	 Btn4 = lvgl.btn_create(Page2,nil)
	 lvgl.obj_set_size(Btn4,70,30)
	 lvgl.obj_align(Btn4,Page2,lvgl.ALIGN_IN_TOP_LEFT,0,130)
	 Btn5 = lvgl.btn_create(Page2,nil)
	 lvgl.obj_set_size(Btn5,70,30)
	 lvgl.obj_align(Btn5,Page2,lvgl.ALIGN_IN_TOP_LEFT,0,170)
     lvgl.page_set_scrollbar_mode(Page2,lvgl.SCROLLBAR_MODE_DRAG)
     lvgl.page_set_edge_flash(Page2,true)
	 lvgl.page_set_anim_time(Page2,500)

	 Label2 = lvgl.label_create(lvgl.scr_act(),nil)
	 lvgl.label_set_text(Label2,"在页面上设置滚动条模式: "..lvgl.page_get_scrollbar_mode(Page2).."\n获取滚动传播属性: "..tostring(lvgl.page_get_scroll_propagation(Page2)).."\n获取边缘闪光效果属性: "..tostring(lvgl.page_get_edge_flash(Page2)).."\n获取可以设置给孩子的宽度仍然不会导致溢出: "..lvgl.page_get_width_fit(Page2).."\n获取可以设置给孩子的高度仍然不会导致溢出: "..lvgl.page_get_height_fit(Page2).."\n除以对象的宽度并获得给定数量的列的宽度:"..lvgl.page_get_width_grid(Page2).."\n除以对象的高度并获得给定数量的列的宽度: "..lvgl.page_get_height_grid(Page2).."\n获取页面可滚动部分的宽度: "..lvgl.page_get_scrl_width(Page2).."\n获取页面可滚动部分的高度: "..lvgl.page_get_scrl_height(Page2).."\n获取页面可滚动部分的布局: "..lvgl.page_get_scrl_layout(Page2).."\n获取最适合的模式: "..lvgl.page_get_scrl_fit_top(Page2).."\n获取底部贴合模式: "..lvgl.page_get_scrl_fit_bottom(Page2))
	 lvgl.obj_align(Label2,nil,lvgl.ALIGN_IN_TOP_RIGHT,0,300)
	 lvgl.obj_add_style(Label2, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)

	 Page3 = lvgl.page_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(Page3,100,150)
	 lvgl.obj_align(Page3,Father,lvgl.ALIGN_IN_TOP_LEFT,0,600)
     Btn1 = lvgl.btn_create(Page3,nil)
	 lvgl.obj_set_size(Btn1,70,30)
	 lvgl.obj_align(Btn1,Page3,lvgl.ALIGN_IN_TOP_LEFT,0,10)
	 lvgl.page_clean(Page3)
	 Btn2 = lvgl.btn_create(Page3,nil)
	 lvgl.obj_set_size(Btn2,50,30)
	 lvgl.obj_align(Btn2,Page3,lvgl.ALIGN_IN_TOP_LEFT,0,50)
	 Btn3 = lvgl.btn_create(Page3,nil)
	 lvgl.obj_set_size(Btn3,50,30)
	 lvgl.obj_align(Btn3,Page3,lvgl.ALIGN_IN_TOP_LEFT,0,90)
	 Btn4 = lvgl.btn_create(Page3,nil)
	 lvgl.obj_set_size(Btn4,50,30)
	 lvgl.obj_align(Btn4,Page3,lvgl.ALIGN_IN_TOP_LEFT,0,130)
	 Btn5 = lvgl.btn_create(Page3,nil)
	 lvgl.obj_set_size(Btn5,50,30)
	 lvgl.obj_align(Btn5,Page3,lvgl.ALIGN_IN_TOP_LEFT,0,170)
     lvgl.page_set_scrollbar_mode(Page3,lvgl.SCROLLBAR_MODE_ON)
    --  lvgl.page_set_scrollable_fit(Page3,lvgl.LAYOUT_COLUMN_RIGHT)

	Label3 = lvgl.label_create(lvgl.scr_act(),nil)
	lvgl.label_set_text(Label3,"在页面上设置滚动条模式: "..lvgl.page_get_scrollbar_mode(Page3).."\n获取滚动传播属性: "..tostring(lvgl.page_get_scroll_propagation(Page3)).."\n获取边缘闪光效果属性: "..tostring(lvgl.page_get_edge_flash(Page3)).."\n获取可以设置给孩子的宽度仍然不会导致溢出: "..lvgl.page_get_width_fit(Page3).."\n获取可以设置给孩子的高度仍然不会导致溢出: "..lvgl.page_get_height_fit(Page3).."\n除以对象的宽度并获得给定数量的列的宽度:"..lvgl.page_get_width_grid(Page3).."\n除以对象的高度并获得给定数量的列的宽度: "..lvgl.page_get_height_grid(Page3).."\n获取页面可滚动部分的宽度: "..lvgl.page_get_scrl_width(Page3).."\n获取页面可滚动部分的高度: "..lvgl.page_get_scrl_height(Page3).."\n获取页面可滚动部分的布局: "..lvgl.page_get_scrl_layout(Page3).."\n获取最适合的模式: "..lvgl.page_get_scrl_fit_top(Page3).."\n获取底部贴合模式: "..lvgl.page_get_scrl_fit_bottom(Page3))
	lvgl.obj_align(Label3,nil,lvgl.ALIGN_IN_TOP_RIGHT,0,600)
	lvgl.obj_add_style(Label3, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)
end