function RollerInit()
   Roller1 = lvgl.roller_create(lvgl.scr_act(),nil)
   lvgl.roller_set_auto_fit(Roller1,false)
   lvgl.obj_set_size(Roller1, 200, 300)
   lvgl.roller_set_visible_row_count(Roller1,5)
   lvgl.roller_set_options(Roller1, "双子座\n双鱼座\n水瓶座\n天秤座\n狮子座\n白羊座\n处女座\n巨蟹座\n天蝎座\n魔羯座", lvgl.ROLLER_MODE_INFINITE)
   lvgl.roller_set_selected(Roller1,2,lvgl.ANIM_ON)
   lvgl.roller_set_align(Roller1,lvgl.LABEL_ALIGN_RIGHT)
   lvgl.obj_align(Roller1,Father, lvgl.ALIGN_IN_TOP_LEFT, 0, 0)
   lvgl.obj_add_style(Roller1, lvgl.ROLLER_PART_BG, demo_ThemeStyle_Bg)

   Label1 = lvgl.label_create(lvgl.scr_act(),nil)
   lvgl.label_set_text(Label1,"获取所选选项的id: "..lvgl.roller_get_selected(Roller1).."\n获取选项总数: "..lvgl.roller_get_option_cnt(Roller1).."\n获取对齐属性: "..lvgl.roller_get_align(Roller1).."\n获取是否启用了自动调整选项"..tostring(lvgl.roller_get_auto_fit(Roller1)).."\n获取动画时间: "..lvgl.roller_get_anim_time(Roller1))
   lvgl.obj_align(Label1,nil,lvgl.ALIGN_IN_TOP_RIGHT,0,0)
   lvgl.obj_add_style(Label1, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)

   Roller2 = lvgl.roller_create(lvgl.scr_act(),nil)
   lvgl.obj_set_size(Roller2, 400, 300)
   lvgl.roller_set_options(Roller2, "双子座\n双鱼座\n水瓶座\n天秤座\n狮子座\n白羊座\n处女座\n巨蟹座\n天蝎座\n魔羯座", lvgl.ROLLER_MODE_NORMAL)
   lvgl.obj_align(Roller2,Father, lvgl.ALIGN_IN_LEFT_MID, 0, 0)
   lvgl.obj_add_style(Roller2, lvgl.ROLLER_PART_BG, demo_ThemeStyle_Bg)
   lvgl.roller_set_align(Roller2,lvgl.LABEL_ALIGN_LEFT)
   lvgl.roller_set_anim_time(Roller2,1000)

   Label2 = lvgl.label_create(lvgl.scr_act(),nil)
   lvgl.label_set_text(Label2,"获取所选选项的id: "..lvgl.roller_get_selected(Roller2).."\n获取选项总数: "..lvgl.roller_get_option_cnt(Roller2).."\n获取对齐属性: "..lvgl.roller_get_align(Roller2).."\n获取是否启用了自动调整选项"..tostring(lvgl.roller_get_auto_fit(Roller2)).."\n获取动画时间: "..lvgl.roller_get_anim_time(Roller2))
   lvgl.obj_align(Label2,nil,lvgl.ALIGN_IN_RIGHT_MID,0,0)
   lvgl.obj_add_style(Label2, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)
end