function TextareaInit()
     Textarea1 = lvgl.textarea_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(Textarea1,350,100)
	 lvgl.textarea_set_text(Textarea1,"")
     lvgl.textarea_set_placeholder_text(Textarea1,"设置默认显示的文本内容")
     lvgl.textarea_set_one_line(Textarea1,true)
     lvgl.textarea_del_char_forward(Textarea1)
	 lvgl.textarea_del_char(Textarea1)
     lvgl.obj_align(Textarea1,Father,lvgl.ALIGN_IN_TOP_MID,0,0)   

	 Textarea2 = lvgl.textarea_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(Textarea2,350,100)
     lvgl.textarea_set_text(Textarea2,"窗前明月光\n疑是地上霜\n举头望明月\n低头思故乡\n")
	 lvgl.textarea_add_text(Textarea2,"xiaobai测试服!\nfskljgalkfja\nfhalfiha\faljfna;\njfs;afja\n")
     lvgl.textarea_add_char(Textarea2,97)
	 lvgl.obj_align(Textarea2,Father,lvgl.ALIGN_IN_TOP_MID,0,40)
     lvgl.textarea_set_cursor_pos(Textarea2,15)
     lvgl.textarea_set_cursor_click_pos(Textarea2,false)

     Label1 = lvgl.label_create(lvgl.scr_act(),nil)
     lvgl.label_set_text(Label1,"\n获取文本区域的文本 : "..tostring(lvgl.textarea_get_text(Textarea2)).."\n获取文本区域的占位符文本: "..lvgl.textarea_get_placeholder_text(Textarea2).."\n获取文本区域的标签: "..tostring(lvgl.textarea_get_label(Textarea2)).."\n获取字符索引中的当前光标位置: "..lvgl.textarea_get_cursor_pos(Textarea2).."\n获取光标是否隐藏: "..tostring(lvgl.textarea_get_cursor_hidden(Textarea2)).."\n获取光标点击定位是否启用: "..tostring(lvgl.textarea_get_cursor_click_pos(Textarea2)).."\n获取密码模式属性: "..tostring(lvgl.textarea_get_pwd_mode(Textarea2)).."\n获取单行配置属性: "..tostring(lvgl.textarea_get_one_line(Textarea2)).."\n获取接受的字符列表: "..tostring(lvgl.textarea_get_accepted_chars(Textarea2)).."\n获取文本区域的最大长度: "..lvgl.textarea_get_max_length(Textarea2).."\n获取文本区域的滚动条模式: "..lvgl.textarea_get_scrollbar_mode(Textarea2).."\n获取滚动传播属性: "..tostring(lvgl.textarea_get_scroll_propagation(Textarea2)).."\n获取滚动传播属性: "..tostring(lvgl.textarea_get_edge_flash(Textarea2)).."\n查看是否启用了选择模式: "..tostring(lvgl.textarea_get_text_sel_en(Textarea2)).."\n设置光标闪烁动画时间: "..lvgl.textarea_get_cursor_blink_time(Textarea2).."\n获取文本滚动条模式: "..tostring(lvgl.textarea_get_scrollbar_mode(Textarea2)))
     lvgl.obj_align(Label1,nil,lvgl.ALIGN_IN_TOP_MID,0,140)
     lvgl.obj_add_style(Label1, lvgl.LABEL_PART_MAIN, demo_ThemeStyle_IndicAndFont)
    
     Textarea3 = lvgl.textarea_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(Textarea3,350,100)
     lvgl.textarea_set_accepted_chars(Textarea3,"明月光地上霜望明月思故乡a\n")
     lvgl.textarea_set_text(Textarea3,"窗前明月光\n疑是地上霜\n举头望明月\n低头思故乡\n")
	 lvgl.textarea_add_text(Textarea3,"xiaobai测试服!\nfskljgalkfja\nfhalfiha\faljfna;\njfs;afja\n")
     lvgl.textarea_add_char(Textarea3,97)
     lvgl.textarea_set_scrollbar_mode(Textarea3,lvgl.SCROLLBAR_MODE_ON)
	 lvgl.obj_align(Textarea3,Father,lvgl.ALIGN_IN_TOP_MID,0,550)
     lvgl.textarea_set_cursor_pos(Textarea3,lvgl.TEXTAREA_CURSOR_LAST)
     lvgl.textarea_set_cursor_hidden(Textarea3,true)
     lvgl.textarea_set_text_align(Textarea3,lvgl.LABEL_ALIGN_RIGHT)
     lvgl.textarea_set_edge_flash(Textarea3,true)
    --  lvgl.textarea_set_text_sel(Textarea3,false)

     Textarea4 = lvgl.textarea_create(lvgl.scr_act(),nil)
     lvgl.obj_set_size(Textarea4,350,100)
     lvgl.textarea_set_text(Textarea4,"窗前明月光\n疑是地上霜\n举头望明月\n低头思故乡\n")
	 lvgl.textarea_add_text(Textarea4,"xiaobai测试服!")
     lvgl.textarea_add_char(Textarea4,97)
	 lvgl.obj_align(Textarea4,Father,lvgl.ALIGN_IN_TOP_MID,0,670)
     lvgl.textarea_set_cursor_pos(Textarea4,lvgl.TEXTAREA_CURSOR_LAST)
     lvgl.textarea_set_cursor_hidden(Textarea4,false)
     lvgl.textarea_set_pwd_mode(Textarea4,true)
     lvgl.textarea_set_cursor_blink_time(Textarea4,1)
     lvgl.textarea_set_pwd_show_time(Textarea4,2000)
    --  lvgl.textarea_set_max_length(Textarea4,5)

end