function TabviewInit()
     Tabview = lvgl.tabview_create(lvgl.scr_act(),nil)
     lvgl.obj_align(Tabview,Father,lvgl.ALIGN_CENTER,0,0)
     lvgl.obj_add_style(Tabview, lvgl.TABVIEW_PART_BG, demo_ThemeStyle_Bg)
	 tab1 = lvgl.tabview_add_tab(Tabview, "星座")
	 tab2 = lvgl.tabview_add_tab(Tabview, "属相")
	 tab3 = lvgl.tabview_add_tab(Tabview, "颜色") 
	 label = lvgl.label_create(tab1,nil)
	 lvgl.label_set_text(label,"狮子座\n白羊座\n射手座\n处女座\n水瓶座\n巨蟹座\n魔羯座\n金牛座\n双子座\n天秤座\n双鱼座\n天蝎座")
     lvgl.tabview_clean_tab(tab1)
	--  lvgl.label_set_text(label,"狮子座\n白羊座\n")
	 label = lvgl.label_create(tab2,nil)
	 lvgl.label_set_text(label,"狮子座\n白羊座\n射手座\n处女座\n水瓶座\n巨蟹座\n魔羯座\n金牛座\n双子座\n天秤座\n双鱼座\n天蝎座")
     lvgl.tabview_set_tab_name(Tabview,2,"天气")
	--  lvgl.tabview_set_tab_act(Tabview,2,"color")
	 lvgl.tabview_set_anim_time(Tabview,2000)
     lvgl.tabview_set_btns_pos(Tabview,lvgl.TABVIEW_TAB_POS_BOTTOM)
end